languageCode = 'en-us'
title = 'Daniel Metz'
author = 'Daniel Metz'
theme = 'hugo-bearblog'
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  favicon = "static/favicon.ico"
  title = "Daniel Metz"
  hideMadeWithLine = true

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNumbersInTable = false
    codeFences = true

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Résumé"
    url = "/resume/"
    weight = 20
  [[menu.main]]
      identifier = "github"
      name = "GitHub"
      url = "https://github.com/danielmmetz"
      weight = 20
